log:
  level: info

runner:
  file: /home/runner/data/.runner
  capacity: 1
  timeout: 3h
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  labels: []

cache:
  enabled: true
  dir: /home/runner/data/.cache/actcache
  host: ""
  port: 0

container:
  network: ""
  privileged: false
  options: ""
  workdir_parent: ""
  valid_volumes:
    - '**'
  # Use Podman instead of Docker
  docker_host: "unix:///run/user/1000/podman/podman.sock"
  force_pull: false
  force_rebuild: false

host:
  workdir_parent: ""
