# Security-focused configuration for act_runner
# This configuration implements defense-in-depth security measures

log:
  level: info

runner:
  file: /home/runner/data/.runner
  capacity: 1
  timeout: 3h
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  labels: []

cache:
  enabled: true
  dir: /home/runner/data/.cache/actcache
  host: ""
  port: 0

container:
  # Use isolated internal network (no internet access)
  network: "restricted-net"
  # Never run in privileged mode
  privileged: false
  # Comprehensive security hardening:
  # --read-only: Root filesystem is read-only
  # --tmpfs /tmp:rw,noexec,nosuid: Writable tmp but cannot execute binaries
  # --security-opt=no-new-privileges: Prevent privilege escalation
  # --cap-drop=ALL: Drop all Linux capabilities
  # -m 2g: Limit memory to 2GB
  # --cpus 2: Limit to 2 CPU cores
  # --pids-limit 100: Limit number of processes to prevent fork bombs
  options: "--read-only --tmpfs /tmp:rw,noexec,nosuid --security-opt=no-new-privileges --cap-drop=ALL -m 2g --cpus 2 --pids-limit 100"
  workdir_parent: ""
  # No volume mounts allowed for security
  valid_volumes: []
  # Use Podman instead of Docker
  docker_host: "unix:///run/user/1000/podman/podman.sock"
  force_pull: false
  force_rebuild: false

host:
  workdir_parent: ""
